### ISSUE TITLE
Wrong date

### ISSUE THREAD

**Issue by Pitel** [499602D2/tg-launchbot#4]
I got this message:

> :loudspeaker: 10 km Flight has been postponed by 1 hour, 30 minutes. SpaceX is now targeting lift-off on March 4th at 23:30 UTC+1.

The date should still be March 3rd.

**Comment by 499602D2** [comment]
Thanks for the issue! The above commit should fix this, but let me know if you see weird dates like that again or if I actually managed to break something — you never know which one it is with dates.
